package InterfazGerente;

import interfaces.fis.login;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author katty
 */
public class PantallaPrincialGerente extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincialGerente
     */
    public PantallaPrincialGerente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPIGerente = new javax.swing.JLabel();
        btnCerraGerente = new javax.swing.JButton();
        btnRegistroEmpleado = new javax.swing.JButton();
        btnSeguimientoPagos = new javax.swing.JButton();
        btnEstudioSE = new javax.swing.JButton();
        btnBajaPaciente = new javax.swing.JButton();
        btnAgendaGeneral = new javax.swing.JButton();
        btnEditarPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPIGerente.setText("PANTALLA DE INICIO DEL GERENTE");

        btnCerraGerente.setText("CERRAR SECION");
        btnCerraGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerraGerenteActionPerformed(evt);
            }
        });

        btnRegistroEmpleado.setText("Registrar empleado");
        btnRegistroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroEmpleadoActionPerformed(evt);
            }
        });

        btnSeguimientoPagos.setText("Seguimiento de pagos");
        btnSeguimientoPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguimientoPagosActionPerformed(evt);
            }
        });

        btnEstudioSE.setText("Estudio socio-economico");
        btnEstudioSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudioSEActionPerformed(evt);
            }
        });

        btnBajaPaciente.setText("Baja paciente");
        btnBajaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaPacienteActionPerformed(evt);
            }
        });

        btnAgendaGeneral.setText("Agenda general");
        btnAgendaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaGeneralActionPerformed(evt);
            }
        });

        btnEditarPaciente.setText("Editar paciente");
        btnEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCerraGerente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAgendaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRegistroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnEstudioSE, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSeguimientoPagos, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(btnBajaPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblPIGerente)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblPIGerente)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroEmpleado)
                    .addComponent(btnSeguimientoPagos))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgendaGeneral)
                    .addComponent(btnBajaPaciente))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarPaciente)
                    .addComponent(btnEstudioSE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnCerraGerente)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerraGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerraGerenteActionPerformed
        login log = new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerraGerenteActionPerformed

    private void btnRegistroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroEmpleadoActionPerformed
        RegistroEmpleado registroEmpleado = new RegistroEmpleado();
        registroEmpleado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroEmpleadoActionPerformed

    private void btnSeguimientoPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguimientoPagosActionPerformed
        SeguimientoPagos seguimientoPagos = new SeguimientoPagos();
        seguimientoPagos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSeguimientoPagosActionPerformed

    private void btnAgendaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaGeneralActionPerformed
        AgendaGeneral agendaGeneral = new AgendaGeneral();
        agendaGeneral.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgendaGeneralActionPerformed

    private void btnBajaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaPacienteActionPerformed
        BajaPaciente bajaPaciente = new BajaPaciente();
        bajaPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBajaPacienteActionPerformed

    private void btnEstudioSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudioSEActionPerformed
        EstudioSE estudioSE = new EstudioSE();
        estudioSE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEstudioSEActionPerformed

    private void btnEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPacienteActionPerformed
        EditarPaciente editarPaciente = new EditarPaciente();
        editarPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincialGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincialGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendaGeneral;
    private javax.swing.JButton btnBajaPaciente;
    private javax.swing.JButton btnCerraGerente;
    private javax.swing.JButton btnEditarPaciente;
    private javax.swing.JButton btnEstudioSE;
    private javax.swing.JButton btnRegistroEmpleado;
    private javax.swing.JButton btnSeguimientoPagos;
    private javax.swing.JLabel lblPIGerente;
    // End of variables declaration//GEN-END:variables
}
